language: node_js
sudo: false
dist: trusty
node_js: stable
addons:
  firefox: latest
  chrome: stable
install:
  - npm i -g bower polymer-cli web-component-tester
  - bower install
before_script:
  - polymer lint
script:
  - polymer test
